/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PresenterRouteImport } from './routes/presenter'
import { Route as AudienceRouteImport } from './routes/audience'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBookmarkDownloadIdRouteImport } from './routes/api/public/bookmark-download.$id'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenterRoute = PresenterRouteImport.update({
  id: '/presenter',
  path: '/presenter',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceRoute = AudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookmarkDownloadIdRoute =
  ApiPublicBookmarkDownloadIdRouteImport.update({
    id: '/api/public/bookmark-download/$id',
    path: '/api/public/bookmark-download/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audience': typeof AudienceRoute
  '/presenter': typeof PresenterRoute
  '/staff': typeof StaffRoute
  '/api/public/bookmark-download/$id': typeof ApiPublicBookmarkDownloadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audience': typeof AudienceRoute
  '/presenter': typeof PresenterRoute
  '/staff': typeof StaffRoute
  '/api/public/bookmark-download/$id': typeof ApiPublicBookmarkDownloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audience': typeof AudienceRoute
  '/presenter': typeof PresenterRoute
  '/staff': typeof StaffRoute
  '/api/public/bookmark-download/$id': typeof ApiPublicBookmarkDownloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audience'
    | '/presenter'
    | '/staff'
    | '/api/public/bookmark-download/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audience'
    | '/presenter'
    | '/staff'
    | '/api/public/bookmark-download/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audience'
    | '/presenter'
    | '/staff'
    | '/api/public/bookmark-download/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AudienceRoute: typeof AudienceRoute
  PresenterRoute: typeof PresenterRoute
  StaffRoute: typeof StaffRoute
  ApiPublicBookmarkDownloadIdRoute: typeof ApiPublicBookmarkDownloadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenter': {
      id: '/presenter'
      path: '/presenter'
      fullPath: '/presenter'
      preLoaderRoute: typeof PresenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audience': {
      id: '/audience'
      path: '/audience'
      fullPath: '/audience'
      preLoaderRoute: typeof AudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookmark-download/$id': {
      id: '/api/public/bookmark-download/$id'
      path: '/api/public/bookmark-download/$id'
      fullPath: '/api/public/bookmark-download/$id'
      preLoaderRoute: typeof ApiPublicBookmarkDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AudienceRoute: AudienceRoute,
  PresenterRoute: PresenterRoute,
  StaffRoute: StaffRoute,
  ApiPublicBookmarkDownloadIdRoute: ApiPublicBookmarkDownloadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
